# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc00ad8437aedab845cdf68114c58cbc6550d752d10a48c6e9a8e41634fe67b2332f4f33a9962bb6adcd7bba74998dbe897512c6d8c0ecb1c151a4d92a957f5c

test:
  secret_key_base: 5da57f93745dd34c5a346be9f78b0d8277894f78e1781c1359f58bced72ac63fed0fd1734f87c0e0150e2589c516ea673c5f19b7299f1c97e1044189163caa19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
