# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:

  secret_key_base: 0ded4b4976a24dee2b6ede58ecbde0b84754c5b00374db756e5857516105b463eb21c2f06d94c3fdddfe67a970f5bdc1f6a673b8657e75c682b5805ca51be4ac

test:
  secret_key_base: 947aad874c686205f873ce1ce882ee656522a91e62de0633eb14fbdf0e3f0268498ddeb576f494f7d48e5680526c88889fd912d57c53a30cf62ef8689f819182

  secret_key_base: 0879c26093141e11bed52ee0c55effeadcbd09f06fd49fde6ab8d252c35602761cf60ae2be3a9eb608c72278114b1fc363f78a1ca01c8464b1db9c5b27b2d775

test:
  secret_key_base: 00986070aa77ceebcb92df54b26969e827a239bddd3e52355f21ede0a17f96dfa266bcf467c91a85a9504f06de3f965c8314d0ad0adee1027b0350edb0aacfba


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
